from exploit.restore import restore_files, FileToRestore, restore_file


device = None



#print(f"Connected to {device.name}\niOS {device.version}\n")

try:
    directory_path = str(input("Directory>> "))
    local_file = str(input("drag and drop file here>> "))
    file_name = str(input("Enter filename>> "))

    with open(local_file, "rb") as f:
        file_content = f.read()

    restore_files(files=[FileToRestore(
                    contents=file_content,
                    restore_path=directory_path,
                    restore_name=file_name
                )], reboot=False, lockdown_client=None)
except Exception as e:
    print(e)